version: '3'

services:
  webp-service:
    image: yhan219/webp-convert-service:1.0
    volumes:
      - $PWD/src/main.go:/src/main.go
    restart: always

  nginx-webp:
    image: nginx:alpine
    container_name: "nginx-webp"
    volumes:
      - $PWD/nginx.conf:/etc/nginx/nginx.conf
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: 10m
        max-file: "3"
        labels: "nginx-webp"
        env: "os"
    ports:
      - "880:80"
    command: nginx -c /etc/nginx/nginx.conf

networks:
  default:
    external:
      name: webp